/**
 * Shared TypeScript types for AI-generated course content
 *
 * These types define the structure of curriculum, sections, content blocks,
 * code examples, and quizzes generated by Claude AI.
 */

// ============================================================================
// SECTION TYPES
// ============================================================================

export type CourseSection = {
  sectionNumber: number;
  title: string;
  description: string;
  learningObjectives: string[];
  estimatedMinutes: number;
  topics: string[];
};

export type ExtendedCourseSection = CourseSection & {
  content: SectionContent;
  quiz: SectionQuiz;
  contentGeneratedAt: string;
  contentGenerationCostUsd: number;
};

// ============================================================================
// CONTENT TYPES
// ============================================================================

export type ContentBlock = {
  type: 'paragraph' | 'heading' | 'list' | 'callout';
  content: string;
  subItems?: string[];
  calloutType?: 'info' | 'warning' | 'tip' | 'example';
  heading?: 'h3' | 'h4';
};

export type CodeExample = {
  title: string;
  description: string;
  language: string;
  code: string;
  explanation: string;
};

export type SectionContent = {
  introduction: string;
  blocks: ContentBlock[];
  codeExamples: CodeExample[];
  summary: string;
  keyTakeaways: string[];
};

// ============================================================================
// QUIZ TYPES
// ============================================================================

export type QuizQuestion = {
  questionText: string;
  questionType: 'multiple_choice' | 'true_false' | 'code_completion';
  options: string[];
  correctAnswer: string;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  codeSnippet?: string;
};

export type SectionQuiz = {
  questions: QuizQuestion[];
};

// ============================================================================
// CURRICULUM TYPES
// ============================================================================

export type CourseCurriculum = {
  courseTitle: string;
  courseDescription: string;
  estimatedDuration: number;
  level: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  sections: CourseSection[];
};

export type ExtendedCourseCurriculum = {
  courseTitle: string;
  courseDescription: string;
  estimatedDuration: number;
  level: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  sections: ExtendedCourseSection[];
};
