version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: kursusaggregator-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=kursus
      - POSTGRES_PASSWORD=kursuspw
      - POSTGRES_DB=kursusdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: kursusaggregator-web
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - DATABASE_URL=postgres://kursus:kursuspw@db:5432/kursusdb
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
    command: npm run dev

volumes:
  db-data:
